### ISSUE TITLE
Calculate

### ISSUE THREAD

**Issue by Yuuzi261** [yuuzi-and-chunill/Blue-Archive-Damage-Calculator#15]
- [ ] - 攻擊技倍率
- [ ] - DEF
- [ ] - 防禦增減技%
- [ ] - 會心傷害%
- [ ] - 技能會心傷害%
- [ ] - 裝備會心傷害抵抗%
- [ ] - 技能會心傷害抵抗%
- [x] - 武器+攻
- [x] - 裝甲克制計算

**Comment by chunill** [comment]
可以做成勾選以後再出現的格子

**Comment by GoldOrange261** [comment]
Fold Button可以取代?

**Comment by GoldOrange261** [comment]
- [ ] 技能倍率
- [ ] 安定率
- [ ] 補正倍率(?
- [ ] 敵防禦減傷
- [ ] 武器分割率
- [ ] (最終會心傷害)
- [ ] 被增減傷Buff&Debuff

**Comment by GoldOrange261** [comment]
()裡的是之後會算
(?是看沒有
